<a href="https://colab.research.google.com/github/sdg331/BDA/blob/main/03w_numpy_handle_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3주차 과제 정리
# 단원 03. 과학용 컴퓨팅 패키지 `numpy`

## 3.1 패키지 numpy 개요와 자료형 ndarray

- numpy는 수치 계산을 빠르게 처리하는 패키지
- 핵심 자료형은 `ndarray`
- `ndarray`는 같은 자료형의 원소로 구성됨
- 배열의 차원, 모양, 자료형 등을 속성으로 확인 가능

In [1]:
# numpy 불러오기
# np라는 별명으로 짧게 사용
import numpy as np

### ndarray 생성

- `np.array()` : 리스트나 튜플을 배열로 변환
- `np.ndarray()` : 지정한 모양의 배열 생성
- `np.ndarray()`는 값을 직접 넣지 않으면 기존 메모리 값이 들어갈 수 있음

In [2]:
# 튜플을 ndarray로 변환
a = np.array((2, 3))
a

array([2, 3])

In [3]:
# ndarray 직접 생성
# 값은 초기화되지 않아서 실행 환경마다 다르게 보일 수 있음
a = np.ndarray((3, 2), dtype=int)
a

array([[      997977858,               0],
       [132010011337936, 132010403482480],
       [132010013936448, 132010014023216]])

In [4]:
# dtype을 두 번째 인자로 지정
a = np.ndarray((3, 2), int)
a

array([[            243589,                  0],
       [              8042,                  0],
       [      734439407616, 178173664552812544]])

### array()와 주요 속성 확인

- `shape` : 배열의 모양
- `ndim` : 차원 수
- `dtype` : 원소 자료형
- `size` : 전체 원소 개수
- `itemsize` : 원소 1개의 바이트 크기
- `nbytes` : 배열 전체 바이트 크기

In [5]:
# int 자료형 배열 생성
a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [6]:
# 배열 객체의 자료형 확인
type(a)

numpy.ndarray

In [7]:
# 배열의 기본 속성 확인
print(a.shape)
print(a.ndim)
print(a.dtype)

# 실행 환경에 따라 int32, int64처럼 다르게 나올 수 있음

(3,)
1
int64


In [8]:
# 원소 개수와 메모리 크기 확인
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


### ndarray의 동일 자료형 특징

- numpy 배열은 모든 원소가 같은 자료형으로 맞춰짐
- 숫자와 문자열이 섞이면 전체가 문자열로 변환됨

In [9]:
# 숫자와 문자열이 섞이면 전체가 문자열 자료형으로 바뀜
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [10]:
# 유니코드 문자열 배열 생성
unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [11]:
# 문자열 길이가 길어도 지정한 문자 자료형 안에서 저장됨
unicode_array = np.array(['가나다라마' * 7, '라마바', '사아자'], dtype='U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

## 3.2 내장함수 arange()와 linspace()

- `np.arange()` : 시작, 끝, 간격을 기준으로 배열 생성
- `np.linspace()` : 시작, 끝, 개수를 기준으로 배열 생성
- `reshape()` : 원소 개수는 유지하면서 배열 모양 변경

### np.arange()

- `np.arange(stop)`
- `np.arange(start, stop)`
- `np.arange(start, stop, step)`
- stop 값은 포함되지 않음

In [12]:
# 정수 범위 배열 생성
print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [13]:
# 실수 범위도 사용 가능
print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


### reshape()

- 배열의 모양을 바꿈
- 전체 원소 개수는 같아야 함
- 원소 개수가 맞지 않으면 오류 발생

In [14]:
# 0부터 11까지 12개 원소 생성 후 3행 4열로 변경
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
# 12개 원소를 2행 6열로 변경
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [260]:
# 오류 예시
# 12개 원소를 3행 5열로 바꾸려고 해서 오류 발생
np.reshape(a, (3, 5))

ValueError: cannot reshape array of size 4 into shape (3,5)

### np.linspace()

- `start` : 시작값
- `stop` : 끝값
- `num` : 생성할 값의 개수
- 기본적으로 끝값을 포함함
- 간격은 자동 계산

In [17]:
# 2.0부터 3.0까지 기본 50개 생성
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [18]:
# retstep=True를 사용하면 간격도 같이 반환
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [19]:
# 기본 50개일 때 간격 계산
print((3 - 2) / (50 - 1))

0.02040816326530612


In [20]:
# endpoint=False면 stop 값 제외
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [21]:
# endpoint=False일 때 간격 계산
print((3 - 2) / 50)

0.02


In [22]:
# 5개의 값 생성
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [23]:
# 5개 생성 + 끝값 제외
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

### arange와 linspace 비교

- `arange`는 간격 중심
- `linspace`는 개수 중심
- 정확히 몇 개로 나눌지 정할 때는 `linspace`가 편함

In [24]:
# arange는 step을 직접 지정
print(np.arange(0, 10, 2))

# linspace는 생성할 개수를 지정
print(np.linspace(0, 10, 6))

[0 2 4 6 8]
[ 0.  2.  4.  6.  8. 10.]


## 3.3 zeros(), ones(), empty()

- `zeros()` : 0으로 채운 배열
- `ones()` : 1로 채운 배열
- `eye()` : 단위행렬
- `full()` : 지정한 값으로 채운 배열
- `empty()` : 초기화하지 않은 배열
- `zeros_like()`, `ones_like()`, `full_like()` : 기존 배열과 같은 모양으로 생성

### np.zeros()

In [25]:
# 0.0으로 채운 1차원 배열
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [26]:
# zeros의 기본 dtype은 float
a.dtype

dtype('float64')

In [27]:
# dtype을 int로 지정
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [28]:
# 2행 1열 배열 생성
b = np.zeros((2, 1))
b

array([[0.],
       [0.]])

### np.ones()

In [29]:
# 1.0으로 채운 2행 4열 배열
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
# 정수형 1로 채운 배열
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

### np.eye()

- 단위행렬 생성
- k를 사용하면 대각선 위치 조정 가능

In [31]:
# 3x3 단위행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
# 정수형 단위행렬
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [33]:
# 3행 4열 형태의 단위행렬
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [34]:
# k=1: 대각선이 오른쪽 위로 이동
np.eye(3, 4, 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
# k=-1: 대각선이 왼쪽 아래로 이동
np.eye(3, 4, -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

### np.full()

- 지정한 모양을 지정한 값으로 채움
- shape과 fill_value의 모양이 맞지 않으면 오류 발생

In [36]:
# 2행 3열을 10으로 채움
np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [37]:
# fill_value가 (1, 2)이면 행마다 반복됨
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [38]:
# range(4)를 3행 4열에 반복
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [39]:
# reshape을 이용해 열 방향으로 값 채우기
np.full([4, 3], fill_value=np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [261]:
# 오류 예시
# (1, 2)는 길이가 2인데 shape은 (2, 3)이라 맞지 않음

np.full([2, 3], (1, 2))

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

### np.empty()

- 지정한 모양의 배열 생성
- 값을 초기화하지 않음
- 실행할 때마다 값이 다르게 보일 수 있음

In [41]:
# 초기화하지 않은 배열
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [42]:
# 2행 2열 빈 배열
np.empty([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [43]:
# 정수형 빈 배열
np.empty([2, 3], dtype=int)

array([[4611686018427387904, 4613487458278336102, 4615288898129284300],
       [4616639978017495449, 4617540697942969548, 4618441417868443647]])

### like 함수

- 기존 배열과 같은 모양으로 새 배열 생성

In [44]:
# 기준 배열 생성
a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [45]:
# 기준 배열과 같은 모양으로 0 채우기
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [46]:
# 기준 배열과 같은 모양으로 1 채우기
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [47]:
# 기준 배열과 같은 모양으로 5 채우기
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

## 3.4 배열 연산

- numpy 배열은 원소별 연산이 가능
- 배열과 스칼라 연산은 모든 원소에 적용됨
- 같은 모양의 배열끼리는 원소별 연산 가능
- 행렬 곱은 `@`, `dot()`, `matmul()` 사용

### 배열과 스칼라 연산

In [48]:
# 1차원 배열 생성
a = np.arange(3)
a

array([0, 1, 2])

In [49]:
# 배열의 모든 원소에 같은 연산 적용
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


### 배열과 배열의 연산

In [50]:
# 2행 3열 배열
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
# a와 같은 모양으로 배열 생성
b = np.full_like(a, [1, 2, 3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [52]:
# 같은 위치의 원소끼리 연산
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


### 복합 대입 연산자

- `+=`, `-=`, `*=`, `/=` 사용 가능
- 정수 배열에 실수를 더해서 저장할 때는 dtype 때문에 오류가 날 수 있음

In [53]:
# 정수 배열
a = np.arange(4)
a

array([0, 1, 2, 3])

In [54]:
# 실수 배열
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [262]:
# 오류 예시
# int 배열 a에 float 결과를 바로 저장하려고 해서 오류 발생 가능
a += b

ValueError: operands could not be broadcast together with shapes (4,) (3,) (4,) 

In [56]:
# 실수 배열 b에는 정수 배열 a를 더해 저장 가능
b += np.arange(4)
b

array([0.5, 2.5, 4.5, 6.5])

### 2차원 배열의 곱 연산자 @

- 앞 배열의 열 수와 뒤 배열의 행 수가 같아야 함
- `(2, 3) @ (3, 2)` 결과는 `(2, 2)`
- 행렬 곱은 교환법칙이 성립하지 않음

In [57]:
# 2행 3열 배열
a = np.full((2, 3), [1, 2, 3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [58]:
# 3행 2열 배열
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [59]:
# @ 연산자
a @ b

array([[12,  6],
       [12,  6]])

In [60]:
# dot() 사용
a.dot(b)

array([[12,  6],
       [12,  6]])

In [61]:
# 순서를 바꾸면 결과 모양이 달라짐
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [62]:
# matmul() 사용
print(np.matmul(a, b))
print(np.matmul(b, a))

[[12  6]
 [12  6]]
[[3 6 9]
 [3 6 9]
 [3 6 9]]


### 배열 함수 sum()

In [63]:
# 합계 계산용 배열
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [64]:
# 전체 원소 합
a.sum()

np.int64(46)

In [65]:
# axis=0: 열 방향 합
a.sum(axis=0)

array([16, 30])

In [66]:
# axis=1: 행 방향 합
a.sum(axis=1)

array([30, 13,  3])

In [67]:
# np.sum() 함수로도 가능
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


### 배열 함수 cumsum()

- 누적합 계산
- axis를 지정하면 방향별 누적합 계산

In [68]:
# 누적합 확인용 배열
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [69]:
# 전체를 1차원처럼 누적
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [70]:
# 열 방향 누적
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [71]:
# 행 방향 누적
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

### 범용 함수

- 배열의 각 원소에 같은 함수를 적용
- `np.add`, `np.divide`, `np.power` 등

In [72]:
# 범용 함수 확인용 배열
a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [73]:
# 같은 모양의 배열 생성
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [74]:
# 덧셈
np.add(a, b)

array([ 3,  6, 11])

In [75]:
# 나눗셈
np.divide(a, b)

array([0.5, 2. , 4.5])

In [76]:
# 거듭제곱
np.power(a, b)

array([ 1, 16, 81])

## 3.5 배열 슬라이싱과 형태 수정

- 1차원 배열은 리스트처럼 인덱싱과 슬라이싱 가능
- 2차원 배열은 행과 열을 함께 지정
- 3차원 배열은 축(axis)을 이해해야 함
- `ravel()`은 1차원 배열로 펼침
- `transpose()`와 `.T`는 축을 바꿈

### 1차원 배열의 첨자와 슬라이싱

In [77]:
# 0부터 9까지 제곱값 배열 생성
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [78]:
# 인덱스 3번 원소
a[3]

np.int64(9)

In [79]:
# numpy 정수를 파이썬 int로 변환
int(a[3])

9

In [80]:
# 뒤에서 두 번째 원소
a[-2]

np.int64(64)

In [81]:
# 1번부터 3번까지
a[1:4]

array([1, 4, 9])

In [82]:
# 뒤에서 5번째부터 뒤에서 2번째까지
a[-5:-1]

array([25, 36, 49, 64])

In [83]:
# 8번에서 3번 전까지 -2 간격으로 이동
a[8:2:-2]

array([64, 36, 16])

In [84]:
# 전체를 순서대로 출력
a[::1]

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [85]:
# 뒤에서부터 -2 간격으로 출력
a[::-2]

array([81, 49, 25,  9,  1])

### 슬라이싱 위치에 대입

- 슬라이싱 결과에 값을 대입 가능
- 여러 값을 넣을 때는 개수가 맞아야 함
- 스칼라 하나는 선택된 부분 전체에 반복 적용됨

In [86]:
# 배열 다시 생성
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [87]:
# 2~4번 위치에 -100 대입
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [88]:
# 배열 다시 생성
a = np.power(np.arange(10), 2)

# 선택한 원소 3개에 값 3개 대입
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [263]:
# 오류 예시
# 선택한 위치는 3개인데 대입할 값은 2개라 오류 발생
a = np.power(np.arange(10), 2)

a[2:5] = [-5, -5]

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [90]:
# 스칼라 값은 선택한 위치 전체에 반복 대입됨
a = np.power(np.arange(10), 2)
a[2:5] = -10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

### 2차원 배열의 첨자와 슬라이싱

- `a[row]` : 행 선택
- `a[:, col]` : 열 선택
- `a[row, col]` : 원소 선택
- `a[, col]`처럼 앞 축을 비우면 오류

In [91]:
# 5행 6열 배열 생성
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [92]:
# 3번 행 선택
a[3]

array([18, 19, 20, 21, 22, 23])

In [93]:
# 마지막 행 선택
a[-1]

array([24, 25, 26, 27, 28, 29])

In [94]:
# 뒤에서 두 번째 행 전체 선택
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [95]:
# 쉼표 뒤를 비워도 행 전체 선택
a[-2,]

array([18, 19, 20, 21, 22, 23])

In [96]:
# 2번 행부터 3번 행까지
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [97]:
# 1번부터 4번 행까지 2칸 간격
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [264]:
# 오류 예시
# a[, 1]처럼 앞 축을 비우면 문법 오류
exec("a[, 1]")

SyntaxError: invalid syntax (<string>, line 1)

In [99]:
# 1번 열 선택
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [100]:
# 1번 열부터 5번 열까지
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [101]:
# 열을 2칸 간격으로 선택
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [102]:
# 2행 4열 원소
a[2, 4]

np.int64(16)

In [103]:
# a[2][4]도 같은 원소를 반환
a[2][4]

np.int64(16)

In [104]:
# 행과 열 범위를 함께 선택
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [105]:
# 전체 행과 전체 열
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [106]:
# 전체 행 선택
a[:,]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [107]:
# 전체 선택
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [108]:
# 행과 열을 모두 역순으로 선택
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [109]:
# 마지막 행과 마지막 열을 제외
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

### 3차원 배열의 이해

- `(2, 3, 4)`는 3행 4열짜리 2차원 배열이 2개 있는 구조로 이해
- axis=0, axis=1, axis=2 순서로 접근

In [110]:
# 3차원 배열 생성
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [111]:
# 같은 원소 개수로 다른 모양 만들기
a.reshape(3, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [112]:
# 원본 a는 그대로
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [113]:
# axis=0의 0번 배열
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
# axis=0의 1번 배열
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [115]:
# 모든 axis=0 배열에서 axis=1의 1번 행 선택
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [116]:
# 모든 axis=0 배열에서 위치 (1, 1) 선택
a[:, 1, 1]

array([ 5, 17])

In [117]:
# 마지막 축(axis=2)의 1번 열 선택
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [118]:
# ...은 중간 축 전체를 의미
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [119]:
# axis=0의 1번, 마지막 축의 1번 선택
a[1, ..., 1]

array([13, 17, 21])

In [120]:
# 위 코드와 같은 의미
a[1, :, 1]

array([13, 17, 21])

In [121]:
# axis=0의 0번 배열 전체
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
# a[0]도 같은 의미
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### ravel()

- 다차원 배열을 1차원으로 펼침

In [123]:
# 2행 3열 2개 구조
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [124]:
# 1차원 배열로 펼치기
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 전치 transpose()

- 2차원에서는 행과 열을 바꿈
- `np.transpose(a)`, `a.transpose()`, `a.T` 모두 사용 가능

In [125]:
# 2행 3열 배열
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
# np.transpose()
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [127]:
# 메소드 transpose()
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [128]:
# T 속성
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 3차원 배열의 전치

- 3차원 배열도 축 순서를 바꿀 수 있음
- `np.transpose(b, (0, 2, 1))`처럼 축 순서를 직접 지정 가능
- 수업 메모: 이 부분은 축 순서 확인이 핵심

In [129]:
# 3차원 배열 생성
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [130]:
# 기본 전치
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [131]:
# 축 순서를 그대로 둠
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [132]:
# b.T와 같은 축 순서
np.transpose(b, (2, 1, 0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [133]:
# axis 1과 axis 2를 교환
np.transpose(b, (0, 2, 1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

### swapaxes(), view, copy

- `swapaxes()` : 두 축만 서로 교환
- view : 원본 데이터를 함께 참조
- copy : 원본과 별도의 새 배열 생성
- view를 수정하면 원본에도 영향을 줄 수 있음

In [134]:
# swapaxes 확인용 배열
x = np.arange(24).reshape(2, 3, 4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [135]:
# axis 0과 axis 2 교환
np.swapaxes(x, 0, 2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [136]:
# swapaxes(x, 0, 2)는 transpose(x, (2, 1, 0))와 같은 모양
print(np.swapaxes(x, 0, 2).shape)
print(np.transpose(x, (2, 1, 0)).shape)

(4, 3, 2)
(4, 3, 2)


In [137]:
# view 예시
original = np.arange(6)
view_arr = original.reshape(2, 3)

print("original:", original)
print("view_arr:")
print(view_arr)
print("view_arr.base:")
print(view_arr.base)

original: [0 1 2 3 4 5]
view_arr:
[[0 1 2]
 [3 4 5]]
view_arr.base:
[0 1 2 3 4 5]


In [138]:
# view를 수정하면 원본도 바뀜
view_arr[0, 0] = 100

print("view_arr:")
print(view_arr)
print("original:", original)

view_arr:
[[100   1   2]
 [  3   4   5]]
original: [100   1   2   3   4   5]


In [139]:
# copy는 원본과 분리됨
original = np.arange(6)
copy_arr = original.copy()

copy_arr[0] = 100

print("original:", original)
print("copy_arr:", copy_arr)
print("copy_arr.base:", copy_arr.base)

original: [0 1 2 3 4 5]
copy_arr: [100   1   2   3   4   5]
copy_arr.base: None


### ndarray와 list의 차이

- list는 길이를 유연하게 바꿀 수 있음
- ndarray는 같은 구조 안에서 빠르게 계산하는 데 초점
- 배열 일부에 여러 값을 넣을 때는 모양이 맞아야 함

In [140]:
# 리스트는 슬라이싱 대입으로 길이가 바뀔 수 있음
lst = [1, 2, 3, 4]
lst[1:3] = [10, 20, 30]
lst

[1, 10, 20, 30, 4]

In [266]:
# ndarray는 선택한 원소 수와 대입할 원소 수가 맞아야 함
arr = np.array([1, 2, 3, 4])

arr[1:3] = [10, 20, 30] # 오류 예시 # 구조를 유지해야 됨

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [142]:
# 원소 수를 맞추면 대입 가능
arr = np.array([1, 2, 3, 4])
arr[1:3] = [10, 20]
arr

array([ 1, 10, 20,  4])

## 3.6 브로드캐스팅

- 모양이 다른 배열끼리도 조건이 맞으면 연산 가능
- 작은 배열을 큰 배열 모양에 맞게 확장해서 계산
- 항상 가능한 것은 아니며, 축의 크기가 맞거나 1이어야 함

### 브로드캐스팅 기본 확인

In [143]:
# 같은 모양의 배열은 바로 연산 가능
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a + b

array([11, 11, 11])

In [267]:
# 오류 예시
# 원소 개수가 맞지 않아 브로드캐스팅 불가능
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])

a + b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

### 2차원 배열과 1차원 배열의 브로드캐스팅

In [145]:
from numpy import arange

# 3행 3열 배열
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
# 1차원 배열
y = arange(-1, 2)
y

array([-1,  0,  1])

In [147]:
# y가 행 방향으로 확장되어 곱셈
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [148]:
# y가 행 방향으로 확장되어 덧셈
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

### 열 방향 브로드캐스팅

In [149]:
# 3행 1열 배열
y = arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [150]:
# 소수점 표시 자리수 조정
np.set_printoptions(precision=2)

In [151]:
# y가 열 방향으로 확장되어 나눗셈
x / y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [152]:
# y가 열 방향으로 확장되어 뺄셈
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

### 행과 열이 1인 배열의 브로드캐스팅

In [153]:
# 1차원 배열
x = arange(1, 4)
x

array([1, 2, 3])

In [154]:
# 3행 1열 배열
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [155]:
# 서로 확장되어 3x3 결과 생성
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [156]:
# 나눗셈도 가능
x / y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [157]:
# 4행 1열 배열
x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [158]:
# 1차원 배열
y = arange(1, 3)
y

array([1, 2])

In [159]:
# 결과는 4행 2열
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [160]:
# 덧셈 결과도 4행 2열
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

### np.newaxis

- `np.newaxis`는 `None`과 같음
- 1차원 배열에 새 축을 추가해 2차원으로 만들 수 있음

In [161]:
from numpy import array

# 1차원 배열
x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [162]:
# np.newaxis는 None과 같음
np.newaxis is None

True

In [163]:
# 행 방향 축 추가
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [164]:
# np.newaxis 사용
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [165]:
# 열 방향 축 추가
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [166]:
# 모양 확인
a.shape

(4, 1)

In [167]:
# 열 벡터와 1차원 배열 브로드캐스팅
a = x[:, np.newaxis]
b = array([1, 2, 3])

print("a shape:", a.shape)
print("b shape:", b.shape)
b

a shape: (4, 1)
b shape: (3,)


array([1, 2, 3])

In [168]:
# 덧셈 결과
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [169]:
# 곱셈 결과
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

## 3.7 고급 색인

- 리스트나 배열을 인덱스로 사용해 여러 원소를 한 번에 선택
- 2차원 배열에서는 행과 열 인덱스의 대응 관계를 주의
- 인덱스 배열의 모양이 맞지 않으면 오류 발생

### 1차원 배열 색인

In [170]:
# 1차원 배열 생성
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
# 일반 인덱싱
x[1]

np.int64(1)

In [172]:
# 슬라이싱
x[:5]

array([0, 1, 2, 3, 4])

In [173]:
# 리스트 인덱싱
print(x[[2]])
print(x[[2, 3]])

[2]
[2 3]


In [174]:
# 여러 위치 선택
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [175]:
# numpy 배열을 인덱스로 사용
x[np.array([5, 3, -4, 8])]

array([5, 3, 6, 8])

In [176]:
# 같은 위치를 여러 번 선택 가능
x[[1, 1, 2, 5]]

array([1, 1, 2, 5])

In [177]:
# 음수 인덱스도 사용 가능
x[[1, 1, 2, 5, -1, -2, -5, -10]]

array([1, 1, 2, 5, 9, 8, 5, 0])

### 2차원 배열 색인 기본

In [178]:
# 7행 8열 배열
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [179]:
# 0번 행
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [180]:
# 0행 1열 원소
x[0, 1]

np.int64(1)

In [181]:
# 5번 행
x[5]

array([40, 41, 42, 43, 44, 45, 46, 47])

In [182]:
# 5번 행과 6번 행
x[[5, 6]]

array([[40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [183]:
# 5행 6열 원소
x[5, 6]

np.int64(46)

In [184]:
# 0번 행과 1번 행
x[[0, 1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [185]:
# 2번 열부터 마지막 열까지
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [269]:
# 오류 예시
# x[, 2:8]은 앞 축이 비어서 문법 오류

x[, 2:8]

SyntaxError: invalid syntax (133134219.py, line 4)

### 열 목록 선택

In [187]:
# 5번 열과 4번 열 선택
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [188]:
# 1번 열만 2차원 형태로 선택
x[:, [1]]

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49]])

In [189]:
# 1번, 2번 열 선택
x[:, [1, 2]]

array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50]])

In [190]:
# 열 순서를 바꾸어 선택
x[:, [2, 1]]

array([[ 2,  1],
       [10,  9],
       [18, 17],
       [26, 25],
       [34, 33],
       [42, 41],
       [50, 49]])

### 행 목록 선택

In [191]:
# 1번 행과 3번 행
x[[1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [192]:
# 위 코드와 같은 의미
x[[1, 3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [193]:
# 전체 배열 다시 확인
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

### 행과 열 참조 매핑

- `x[[1, 3], [2, 2]]`는 `x[1,2]`, `x[3,2]`를 선택
- 두 인덱스 배열의 모양이 맞아야 함

In [194]:
# 1행 2열 원소를 배열 형태로 반환
x[[1], [2]]

array([10])

In [195]:
# 1행 2열, 3행 2열 선택
x[[1, 3], [2, 2]]

array([10, 26])

In [270]:
# 오류 예시
# 행 인덱스 2개, 열 인덱스 3개라 모양이 맞지 않음

x[[1, 3], [2, 2, 3]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [197]:
# 열 인덱스 [2]는 브로드캐스팅되어 사용 가능
x[[1, 3], [2]]

array([10, 26])

In [198]:
# 스칼라 열 인덱스도 가능
x[[1, 3], 2]

array([10, 26])

### 브로드캐스팅되는 고급 색인

In [199]:
# 0, 2, 4행에서 1번 열 선택
x[[0, 2, 4], 1]

array([ 1, 17, 33])

In [271]:
# 오류 예시
# 행 인덱스 3개와 열 인덱스 2개는 바로 대응 불가능
x[[0, 2, 4], [0, 1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [201]:
# 각 원소 직접 확인
print(x[0, 1])
print(x[2, 1])
print(x[4, 1])

1
17
33


In [202]:
# 0, 2, 4행에서 앞의 두 열 선택
x[[0, 2, 4], :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

### 기본 색인과 고급 색인 조합

In [203]:
# 5행 8열 배열
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [204]:
# 2~3행, 3~6열 선택
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [205]:
# arange로 행 번호 만들기
np.arange(2, 4)

array([2, 3])

In [206]:
# arange 결과를 행 인덱스로 사용
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [207]:
# 위 코드와 같은 의미
a[[2, 3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [208]:
# 선택한 행에서 열 순서를 바꿔 선택
a[np.arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [209]:
# 2~4행 선택
a[np.arange(2, 5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [210]:
# 선택한 행에서 여러 열 선택
a[np.arange(2, 5)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [211]:
# 음수 방향 열 인덱스 만들기
np.arange(-1, -8, -1)

array([-1, -2, -3, -4, -5, -6, -7])

In [212]:
# 선택한 행에서 열을 뒤에서부터 역순으로 선택
a[np.arange(2, 5)][:, np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])