<a href="https://colab.research.google.com/github/sdg331/BDA/blob/main/04w_array_stack_split_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 04주차 | 다차원 배열 결합과 분리


In [1]:
# 기본 패키지 불러오기
# numpy 배열 결합/분리 실습에 사용
import numpy as np

# 출력이 너무 길 때 보기 좋게 설정
np.set_printoptions(precision=3, suppress=True)

## 4.1 배열 결합

- `vstack()` : 세로 방향 결합
- `hstack()` : 가로 방향 결합
- `column_stack()` : 열 방향 결합
- `row_stack()` : `vstack()`과 거의 같은 기능
- `concatenate()` : 축을 지정해서 결합
- `stack()` : 새 축을 추가해서 차원을 하나 늘려 결합

### 1. `np.vstack()` : 2차원 배열 세로 결합

- 축 0 방향으로 결합
- 열 수가 같아야 함

In [2]:
# np.vstack()
# 3행 2열 배열 생성
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
# 같은 열 수를 가진 배열 생성
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
# 세로로 결합
# 결과: 6행 2열
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

### 2. `np.vstack()` : 1차원 배열 결합

- 1차원 배열을 세로로 쌓으면 2차원 배열이 됨
- 각 배열의 길이가 같아야 함

In [5]:
# 1차원 배열 2개 생성
x = np.array([1, 2, 3])
y = np.array([5, 6, 7])

# 1D -> 2D
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

### 3. `np.hstack()` : 2차원 배열 가로 결합

- 축 1 방향으로 결합
- 행 수가 같아야 함

In [6]:
# 3행 2열 배열 생성
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
# 3행 3열 배열 생성
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [8]:
# 가로로 결합
# 결과: 3행 5열
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

### 4. `np.hstack()` : 1차원 배열 결합

- 1차원 배열은 길이가 달라도 이어 붙일 수 있음
- 결과도 1차원 배열

In [9]:
# 1차원 배열 수평 결합
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

### 5. `np.column_stack()` : 1차원 배열을 열로 결합

- 1차원 배열을 자동으로 열 벡터처럼 바꾼 후 결합
- `hstack()`과 결과가 다를 수 있음

In [10]:
# 1차원 배열 생성
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

# 열 방향으로 결합
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [11]:
# 1차원 배열 x의 모양 확인
x.shape

(3,)

In [12]:
# np.newaxis로 열 방향 차원 추가
# (3,) -> (3, 1)
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [13]:
# None도 np.newaxis와 같은 역할
x[:, None]

array([[1],
       [2],
       [3]])

In [14]:
# 이미 열 벡터로 바꾼 뒤 column_stack 적용
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [15]:
# hstack은 1차원 배열을 그대로 이어 붙임
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [16]:
# column_stack과 hstack은 같은 함수가 아님
np.column_stack == np.hstack

False

### 6. `column_stack()`과 `hstack()`의 차이 보충

- 1차원 배열에서는 결과가 다름
- 2차원 배열에서는 비슷하게 동작할 수 있음

In [17]:
# 1차원 배열 준비
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print('column_stack 결과')
print(np.column_stack((x, y)))

print('hstack 결과')
print(np.hstack((x, y)))

column_stack 결과
[[ 1 10]
 [ 2 20]
 [ 3 30]]
hstack 결과
[ 1  2  3 10 20 30]


In [18]:
# 2차원 배열 준비
x2 = np.arange(1, 7).reshape(2, 3)
y2 = np.arange(7, 13).reshape(2, 3)

print(x2)
print(y2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [19]:
# 2차원에서는 둘 다 가로 결합처럼 동작
print(np.column_stack((x2, y2)))
print(np.hstack((x2, y2)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### 7. `np.row_stack()`

- `vstack()`과 같은 기능
- 강의자료에서는 향후 없어질 수 있으므로 `vstack()` 사용을 권장

In [20]:
# 2행 3열 배열
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
# 4행 3열 배열
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [22]:
# row_stack으로 세로 결합
np.row_stack((a, b))

/tmp/ipykernel_5264/2337311269.py:2: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [23]:
# vstack과 결과 비교
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

### 8. `np.concatenate()` : 1차원 배열 결합

- 기본은 `axis=0`
- 1차원 배열은 축 0만 존재
- `axis=1`은 오류 발생

In [24]:
# 1차원 배열 3개 생성
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

a, b, c

(array([1, 2]), array([3, 4]), array([5, 6]))

In [25]:
# 기본 결합
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [26]:
# axis=0 결합
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [27]:
# axis=None이면 모두 펼쳐서 결합
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [28]:
# 오류 예시
# 1차원 배열에는 axis=1이 없음
np.concatenate((a, b, c), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

### 9. `np.concatenate()` : 2차원 배열 결합

- `axis=0` : 세로 결합, 열 수가 같아야 함
- `axis=1` : 가로 결합, 행 수가 같아야 함
- `axis=None` : 배열을 1차원으로 펼쳐 결합

In [126]:
# 2행 3열 배열
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [127]:
# 2행 3열 배열
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [128]:
# 2행 2열 배열
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [129]:
# 기본 axis=0
# 세로 결합
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [130]:
# axis=0 명시
np.concatenate((x, y), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [131]:
# vstack과 같은 결과
np.vstack((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [132]:
# axis=1
# 가로 결합
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [133]:
# x와 z는 행 수가 같으므로 axis=1 가능
np.concatenate((x, z), axis=1)

array([[ 0,  1,  2, 20, 21],
       [ 3,  4,  5, 22, 23]])

In [134]:
# axis=None은 평면화 후 연결
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [135]:
# 오류 예시
# axis=0은 열 수가 같아야 하는데 x와 z는 열 수가 다름
np.concatenate((x, z), axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

### 10. `np.stack()` : 1차원 배열 결합

- 기존 축에 붙이는 것이 아니라 새 축을 만들어 결합
- 차원이 하나 증가함

In [136]:
# 1차원 배열 생성
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [137]:
# 1차원 배열 생성
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [138]:
# 기본 axis=0
# row_stack과 비슷한 모양
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
# axis=1
# column_stack과 비슷한 모양
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [140]:
# axis=-1은 마지막 축
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [141]:
# 비교
print('row_stack')
print(np.row_stack((a, b)))
print('column_stack')
print(np.column_stack((a, b)))

row_stack
[[1 2 3]
 [4 5 6]]
column_stack
[[1 4]
 [2 5]
 [3 6]]


/tmp/ipykernel_5264/4158654680.py:3: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a, b)))


### 11. 3차원 배열 이해

- 3차원 배열은 2차원 배열이 여러 개 모인 형태로 이해
- `shape`의 의미를 같이 확인

In [142]:
# shape (3, 3, 2)
# 3행 2열 배열이 3개 있는 구조
arr_332 = np.arange(1, 19).reshape(3, 3, 2)
arr_332

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [143]:
# shape 확인
arr_332.shape

(3, 3, 2)

In [144]:
# shape (2, 2, 4)
# 2행 4열 배열이 2개 있는 구조
arr_224 = np.arange(16).reshape(2, 2, 4)
arr_224

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [145]:
# shape 확인
arr_224.shape

(2, 2, 4)

### 12. `np.stack()` : 2차원 배열을 3차원으로 결합

- 같은 모양의 2차원 배열을 결합
- `axis=0`, `axis=1`, `axis=2`에 따라 결과 모양이 달라짐

In [146]:
# 같은 모양의 2차원 배열 3개 생성
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [147]:
# 두 번째 배열
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [148]:
# 세 번째 배열
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [149]:
# axis=0으로 결합
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [150]:
# axis=0 결과 모양
ax0.shape

(3, 2, 3)

In [151]:
# axis=1로 결합
ax1 = np.stack((x, y, z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [152]:
# axis=1 결과 모양
ax1.shape

(2, 3, 3)

In [153]:
# axis=2로 결합
ax2 = np.stack((x, y, z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [154]:
# axis=2 결과 모양
ax2.shape

(2, 3, 3)

In [155]:
# 세 배열 원본 확인
print(x)
print()
print(y)
print()
print(z)
print()

[[0 1 2]
 [3 4 5]]

[[10 11 12]
 [13 14 15]]

[[20 21 22]
 [23 24 25]]



In [156]:
# axis별 stack 결과 한 번에 확인
print('np.stack((x, y, z), axis=0)')
print(np.stack((x, y, z), axis=0))
print()
print('np.stack((x, y, z), axis=1)')
print(np.stack((x, y, z), axis=1))
print()
print('np.stack((x, y, z), axis=2)')
print(np.stack((x, y, z), axis=2))

np.stack((x, y, z), axis=0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]

np.stack((x, y, z), axis=1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]

np.stack((x, y, z), axis=2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


### 13. `np.stack(axis=2)` 과정 확인

- `np.newaxis` 또는 `expand_dims()`로 축 2를 추가
- 그 뒤 `concatenate(axis=2)`로 붙이는 것과 비슷하게 이해 가능

In [157]:
# x에 마지막 축 추가
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [158]:
# y에 마지막 축 추가
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [159]:
# z에 마지막 축 추가
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [160]:
# expand_dims로 같은 결과 확인
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [161]:
# axis=2로 확장한 배열을 concatenate
np.concatenate((x[:, :, np.newaxis], y[:, :, np.newaxis], z[:, :, np.newaxis]), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [162]:
# stack(axis=2)와 같은 결과인지 확인
np.array_equal(
    np.stack((x, y, z), axis=2),
    np.concatenate((x[:, :, np.newaxis], y[:, :, np.newaxis], z[:, :, np.newaxis]), axis=2)
)

True

### 14. 열 벡터로 바꾼 뒤 결합하기

- `hstack()`은 2차원 배열끼리 결합해야 안정적
- 1차원 배열 `c`는 `(3, 1)`로 바꿔 붙임

In [163]:
# 3행 4열 배열과 1차원 배열 생성
a = np.arange(1, 13).reshape(3, 4)
c = np.arange(1, 6, 2)
a, c

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([1, 3, 5]))

In [164]:
# c를 열 벡터로 바꾸기
c[:, None]

array([[1],
       [3],
       [5]])

In [165]:
# np.newaxis 사용
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [166]:
# expand_dims 사용
cc = np.expand_dims(c, axis=1)
cc

array([[1],
       [3],
       [5]])

In [167]:
# 2차원 배열끼리 hstack 가능
np.hstack((a, cc))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [168]:
# 오류 예시
# 2차원 배열 a와 1차원 배열 c는 hstack에서 차원이 맞지 않음
np.hstack((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [169]:
# column_stack은 1차원 c를 열로 바꿔 결합
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [170]:
# c가 이미 2차원이어도 column_stack 가능
np.column_stack((a, cc))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

### 15. `row_stack()`과 `vstack()` 비교

- 열 수가 같으면 2차원 배열과 1차원 배열도 세로 결합 가능

In [171]:
# 3행 4열 배열
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [172]:
# 길이 4인 1차원 배열
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [173]:
# row_stack으로 결합
np.row_stack((a, b))

/tmp/ipykernel_5264/580362223.py:2: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [174]:
# vstack으로 결합
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

### 16. `np.c_[]` : 열 방향 결합

- 함수 호출이 아니라 대괄호 `[]` 사용
- 1차원 배열을 자동으로 열 벡터처럼 바꿔 결합

In [175]:
# 1차원 배열 생성
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [176]:
# np.c_로 열 결합
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [177]:
# 괄호로 묶은 경우도 확인
np.c_[(a, b)]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [178]:
# column_stack과 비교
np.c_[a, b], np.column_stack((a, b))

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [179]:
# hstack은 1차원으로 이어 붙임
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [180]:
# r_도 1차원으로 이어 붙임
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [181]:
# concatenate도 1차원으로 이어 붙임
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

### 17. `np.c_[]`와 `np.column_stack()` : 2차원 배열

- 2차원 배열에서는 수평 결합처럼 동작
- 스칼라도 중간에 넣을 수 있음

In [182]:
# 1행 3열 배열 2개 생성
x = np.arange(1, 4).reshape(1, 3)
y = np.arange(4, 7).reshape(1, 3)
x, y

(array([[1, 2, 3]]), array([[4, 5, 6]]))

In [183]:
# np.c_로 열 방향 결합
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [184]:
# column_stack도 같은 결과
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [185]:
# 스칼라 값도 중간에 삽입 가능
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [186]:
# column_stack에서도 스칼라 결합 가능
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

### 18. `np.r_[]` 기본 사용

- 여러 배열이나 슬라이스를 이어 붙일 수 있음
- 슬라이스 표현을 `arange`, `linspace`처럼 사용할 수 있음

In [187]:
# 1차원 배열 결합
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [188]:
# start:stop:step 형태
# arange(3, 10, 3)과 비슷
np.r_[3:10:3, [0] * 2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [189]:
# start:stop:numj 형태
# -1부터 1까지 6개로 나눔
np.r_[-1:1:6j, [0] * 2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [190]:
# linspace와 비교
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

### 19. `np.r_['i', ...]` : 결합 축 지정

- 문자열로 결합 축을 지정할 수 있음
- 2차원 배열에서 `'0'`은 세로 결합, `'-1'` 또는 `'1'`은 가로 결합

In [191]:
# 2차원 배열 생성
a2 = np.array([[0, 1, 2], [3, 4, 5]])
a2

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
# 기본 r_는 axis=0 방향 결합
np.r_[a2, a2, a2]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [65]:
# 문자열 '0' : axis=0
np.r_['0', a2, a2]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [66]:
# 문자열 '-1' : 마지막 축 방향 결합
np.r_['-1', a2, a2]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [67]:
# 문자열 '1' : axis=1 방향 결합
np.r_['1', a2, a2]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [68]:
# c_는 열 방향 결합
np.c_[a2, a2]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### 20. `np.r_['i, j', ...]` : 최소 차원 강제

- 첫 번째 값 `i` : 결합 축
- 두 번째 값 `j` : 최소 차원 수
- 1차원 배열을 2차원으로 바꿔 결합할 때 사용

In [69]:
# 1차원 배열 생성
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [70]:
# 1차원 배열을 수평 방향으로 결합
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [71]:
# 1차원 배열을 2차원으로 만든 뒤 axis=0으로 결합
# vstack과 비슷한 결과
np.r_['0,2', a, b]

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
# vstack과 비교
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
# 1차원 배열을 열로 바꿔 axis=1로 결합
np.r_['-1,2,0', a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [74]:
# 같은 기능: np.r_['1,2,0', a, b]
np.r_['1,2,0', a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
# c_와 비교
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

### 21. `np.r_['i, j, k', ...]` : 차원 확장 위치 지정

- `i` : 결합 축
- `j` : 최소 차원 수
- `k` : 원래 배열의 축이 들어갈 위치
- 강의자료의 중간고사 제외 범위도 코드 확인용으로 정리함

In [76]:
# k=0 : (3,) -> (3, 1) 형태로 확장 후 axis=0 결합
np.r_['0,2,0', a, b]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [77]:
# k=1 또는 기본값 : (3,) -> (1, 3) 형태로 확장 후 axis=0 결합
np.r_['0,2,1', a, b]

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
# 최소 3차원, k=0
# (3,) -> (3, 1, 1)
np.r_['0,3,0', a, b]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [79]:
# 결과 모양 확인
np.r_['0,3,0', a, b].shape

(6, 1, 1)

In [80]:
# 최소 3차원, k=1
# (3,) -> (1, 3, 1)
np.r_['0,3,1', a, b]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [81]:
# 결과 모양 확인
np.r_['0,3,1', a, b].shape

(2, 3, 1)

In [82]:
# 최소 3차원, k=2
# (3,) -> (1, 1, 3)
np.r_['0,3,2', a, b]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [83]:
# 결과 모양 확인
np.r_['0,3,2', a, b].shape

(2, 1, 3)

### 22. `np.matrix`와 `np.r_` 출력 옵션

- `np.matrix()`는 특수한 2차원 행렬 객체
- `r`, `c` 옵션은 1차원 결과를 행렬처럼 출력할 때 사용

In [84]:
# matrix 객체 생성
m = np.matrix('1 2; 3 4')
m

matrix([[1, 2],
        [3, 4]])

In [85]:
# 행렬 곱셈
m @ m

matrix([[ 7, 10],
        [15, 22]])

In [86]:
# r 옵션: 1 x N matrix 형태
np.r_['r', a, b]

matrix([[1, 2, 3, 4, 5, 6]])

In [87]:
# c 옵션: N x 1 matrix 형태
np.r_['c', a, b]

matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

### 23. 1차원 배열 결합 방법 정리 코드

- 수평 결합: `hstack`, `r_`, `concatenate`
- 수직 결합: `vstack`, `row_stack`, `r_['0,2']`
- 열 결합: `column_stack`, `c_`, `r_['-1,2,0']`

In [88]:
# 1차원 배열 준비
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print('수평 결합')
print(np.hstack((a, b)))
print(np.r_[a, b])
print(np.concatenate((a, b)))

print()
print('수직 결합')
print(np.vstack((a, b)))
print(np.row_stack((a, b)))
print(np.r_['0,2', a, b])

print()
print('열 결합')
print(np.column_stack((a, b)))
print(np.c_[a, b])
print(np.r_['-1,2,0', a, b])

수평 결합
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]

수직 결합
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]

열 결합
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


/tmp/ipykernel_5264/1642026427.py:13: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a, b)))


## 4.2 배열 분리

- `split()` : 배열을 여러 부분으로 분리
- `hsplit()` : 축 1 방향 분리
- `vsplit()` : 축 0 방향 분리
- `array_split()` : 균등하게 나누어지지 않아도 분리 가능
- `dsplit()` : 3차원 이상에서 축 2 방향 분리

### 1. `np.split()` : 1차원 배열 균등 분리

- 반환값은 배열들의 리스트
- 정수로 나눌 때는 같은 크기로 나누어져야 함

In [89]:
# 0.0부터 8.0까지 1차원 배열
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [90]:
# 3개로 균등 분리
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [91]:
# 분리 결과 자료형 확인
print(type(s))
for part in s:
    print(part, part.shape)

<class 'list'>
[0. 1. 2.] (3,)
[3. 4. 5.] (3,)
[6. 7. 8.] (3,)


### 2. `np.split()` : 인덱스 위치 기준 분리

- `[i, j, k]`를 넣으면 구간 기준으로 분리
- 예: `[2, 6]`이면 `[:2]`, `[2:6]`, `[6:]`

In [92]:
# 10부터 60까지 10 간격 배열
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [93]:
# 인덱스 기준으로 여러 구간 분리
np.split(y, [2, 3, 4, 6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [94]:
# 1부터 9까지 배열
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
# [2, 6] 기준 분리
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

### 3. 2차원 배열의 `split(axis=1)`과 `hsplit()`

- 축 1 방향으로 분리
- 열 방향으로 자른다고 이해

In [96]:
# 2행 12열 배열 생성
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [97]:
# hsplit으로 3개 분리
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [98]:
# split(axis=1)도 같은 기능
np.split(a, 3, axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [99]:
# 4개로도 균등 분리 가능
np.split(a, 4, axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [100]:
# 인덱스 기준으로 열 분리
np.split(a, [3, 5, 7], axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

### 4. 2차원 배열의 `split(axis=0)`과 `vsplit()`

- 축 0 방향으로 분리
- 행 방향으로 자른다고 이해

In [101]:
# 6행 4열 배열
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [102]:
# 축 0 기준으로 3개 분리
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [103]:
# 인덱스 기준 분리
np.split(b, [2, 4, 6], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

### 5. `np.hsplit()` : 1차원 배열과 2차원 배열

- 1차원 배열도 분리 가능
- 2차원 배열에서는 열 방향 분리

In [104]:
# 1차원 배열
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
# 2개로 균등 분리
np.hsplit(arr, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [106]:
# 인덱스 기준 분리
np.hsplit(arr, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [107]:
# 2차원 배열 준비
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [108]:
# (3, 5, 8) 기준으로 열 분리
np.hsplit(a, (3, 5, 8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [109]:
# 앞부분 슬라이싱 확인
a[:, :3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [110]:
# 마지막 부분 슬라이싱 확인
a[:, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

### 6. `np.vsplit()` : 2차원 배열 행 방향 분리

- 축 0 기준으로 분리
- 균등 분리가 안 되면 오류 발생

In [111]:
# 6행 3열 배열
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [112]:
# 3개로 균등 분리
np.vsplit(a, 3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [113]:
# 오류 예시
# 6행을 4개로 균등 분리할 수 없음
np.vsplit(a, 4)

ValueError: array split does not result in an equal division

In [192]:
# 인덱스 기준 분리
np.vsplit(a, (1, 4, 6))

ValueError: vsplit only works on arrays of 2 or more dimensions

In [193]:
# 슬라이싱으로 같은 구간 확인
a[:1, :]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [194]:
# 중간 구간 확인
a[4:6, :]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [195]:
# 마지막 빈 구간 확인
a[6:, :]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### 7. 3차원 배열의 `vsplit()`

- `vsplit()`은 무조건 축 0 기준
- `np.split(x, n, axis=0)`과 같음

In [196]:
# 4행 4열 2개 깊이의 3차원 배열
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [197]:
# split(axis=0)
np.split(x, 2, axis=0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [198]:
# vsplit과 같은 결과
np.vsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [199]:
# 축 0 기준 슬라이싱
x[:1, :, :]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [200]:
# 축 0 기준 중간 구간
x[1:3]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [201]:
# 축 0 기준 마지막 구간
x[3:]

array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [202]:
# 인덱스 [1, 3] 기준 분리
np.vsplit(x, [1, 3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

### 8. 3차원 배열의 `hsplit()`

- 3차원 이상에서 `hsplit()`은 축 1 기준
- `np.split(x, n, axis=1)`과 같음

In [203]:
# 3차원 배열 확인
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [204]:
# hsplit으로 2개 분리
np.hsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [205]:
# split(axis=1)과 같은 결과
np.split(x, 2, axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [206]:
# 인덱스 기준 분리
np.hsplit(x, [1, 3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

### 9. `np.array_split()` : 균등하지 않아도 분리 가능

- `split()`은 균등하게 안 나누어지면 오류
- `array_split()`은 가능한 크기로 나누어 반환

In [207]:
# 길이 9인 배열
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [208]:
# 5개로 균등하지 않게 분리 가능
np.array_split(x, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8])]

In [209]:
# split은 같은 상황에서 오류 발생
np.split(x, 5)

ValueError: array split does not result in an equal division

### 10. 2차원 `np.array_split()`

- `axis=0` : 행 방향 분리
- `axis=1` : 열 방향 분리
- 인덱스 리스트도 사용 가능

In [210]:
# 4행 6열 배열
x = np.arange(24).reshape(4, 6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [211]:
# axis=0 기준 3개 분리
np.array_split(x, 3, axis=0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]])]

In [212]:
# axis=1 기준 4개 분리
np.array_split(x, 4, axis=1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]),
 array([[ 4],
        [10],
        [16],
        [22]]),
 array([[ 5],
        [11],
        [17],
        [23]])]

In [213]:
# [2, 4] 기준 axis=0 분리
np.array_split(x, [2, 4], axis=0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([], shape=(0, 6), dtype=int64)]

In [214]:
# [2, 4] 기준 axis=1 분리
np.array_split(x, [2, 4], axis=1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

### 11. 3차원 배열에서 `array_split(axis=2)`

- 3차원 배열은 축 0, 1, 2를 가짐
- `axis=2`는 마지막 축 방향 분리

In [215]:
# shape (2, 2, 6)
a = np.arange(24).reshape(2, 2, 6)
a

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [216]:
# 마지막 축 기준으로 4개 분리
np.array_split(a, 4, axis=2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [217]:
# 각 부분 배열의 shape 확인
for part in np.array_split(a, 4, axis=2):
    print(part.shape)

(2, 2, 2)
(2, 2, 2)
(2, 2, 1)
(2, 2, 1)


In [218]:
# shape (3, 3, 4) 예시
b = np.arange(36).reshape(3, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [219]:
# axis=2 기준 2개 분리
np.array_split(b, 2, axis=2)

[array([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],
 
        [[12, 13],
         [16, 17],
         [20, 21]],
 
        [[24, 25],
         [28, 29],
         [32, 33]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]],
 
        [[26, 27],
         [30, 31],
         [34, 35]]])]

### 12. `np.dsplit()` : 3차원 이상에서 깊이 방향 분리

- `dsplit()`은 축 2 기준
- 3차원 이상의 배열에만 사용 가능

In [220]:
# 3차원 배열 생성
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [221]:
# dsplit으로 3개 분리
np.dsplit(x, 3)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4,  5],
         [10, 11]],
 
        [[16, 17],
         [22, 23]]])]

In [222]:
# 인덱스 기준 분리
np.dsplit(x, [2, 4, 5])

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [223]:
# 오류 예시
# 6개를 4개로 균등 분리할 수 없음
np.dsplit(x, 4)

ValueError: array split does not result in an equal division

In [224]:
# 오류 예시
# dsplit은 3차원 이상에서 사용 가능
np.dsplit(np.arange(6).reshape(2, 3), 1)

ValueError: dsplit only works on arrays of 3 or more dimensions

## 4.3 numpy의 난수와 다양한 함수

- `default_rng()` : 새로운 방식의 난수 생성기
- `random()` : `[0, 1)` 범위 실수 난수
- `integers()` : 정수 난수
- `standard_normal()` : 표준정규분포 난수
- 기존 `np.random` 방식과 새 `Generator` 방식을 같이 확인

### 1. 난수 생성기 기본

- 시드 값이 같으면 같은 순서의 난수가 만들어짐
- 재현 가능한 실습에 유용

In [225]:
# 난수 생성기 만들기
rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x7B5000066B20

In [226]:
# 다른 시드로 난수 생성기 만들기
rg = np.random.default_rng(1)
rg

Generator(PCG64) at 0x7B5000066DC0

In [227]:
# 시드 1로 난수 하나 생성
rg = np.random.default_rng(1)
rg.random()

0.5118216247002567

### 2. `random()` : 실수 난수

- 범위는 `[0, 1)`
- 크기를 지정하면 배열 형태로 생성

In [228]:
# 실수 난수 1개
rg = np.random.default_rng(12)
r = rg.random()
r

0.2508244581084461

In [229]:
# 실수 난수 4개
rg.random(4)

array([0.947, 0.189, 0.179, 0.35 ])

In [230]:
# 실수 난수 5개
rg.random(5)

array([0.231, 0.67 , 0.115, 0.896, 0.858])

In [231]:
# 4행 3열 실수 난수
rg.random((4, 3))

array([[0.003, 0.541, 0.107],
       [0.258, 0.417, 0.454],
       [0.468, 0.928, 0.259],
       [0.188, 0.671, 0.947]])

In [232]:
# 3차원 실수 난수
rg.random((3, 4, 2))

array([[[0.923, 0.88 ],
        [0.064, 0.937],
        [0.649, 0.872],
        [0.408, 0.219]],

       [[0.793, 0.662],
        [0.779, 0.201],
        [0.134, 0.764],
        [0.02 , 0.946]],

       [[0.135, 0.6  ],
        [0.419, 0.324],
        [0.17 , 0.78 ],
        [0.915, 0.729]]])

### 3. 기존 `np.random` 방식

- 기존 방식도 코드에서 많이 사용됨
- 새 방식인 `default_rng()`가 더 권장됨

In [233]:
# 기존 방식의 실수 난수
np.random.random()

0.3914470331786538

In [234]:
# from numpy import random 방식
from numpy import random
random.random()

0.7638265433607958

In [235]:
# 기존 방식의 정수 난수
np.random.randint(1, 10, 15)

array([3, 1, 4, 6, 9, 9, 1, 8, 8, 8, 2, 4, 8, 6, 1])

In [236]:
# 기존 방식의 0~1 실수 난수 배열
np.random.rand(3, 4)

array([[0.412, 0.637, 0.805, 0.969],
       [0.62 , 0.772, 0.225, 0.927],
       [0.266, 0.371, 0.34 , 0.178]])

In [237]:
# 출력 자릿수 설정 후 확인
np.set_printoptions(precision=3)
np.random.rand(5, 3)

array([[0.422, 0.089, 0.933],
       [0.585, 0.794, 0.721],
       [0.974, 0.316, 0.373],
       [0.399, 0.977, 0.723],
       [0.648, 0.096, 0.004]])

### 4. `integers()` : 정수 난수

- `[low, high)` 범위에서 정수 난수 생성
- `high` 값은 포함하지 않음

In [238]:
# low=0, high=10 범위에서 정수 난수 3개
rg = np.random.default_rng(12345)
r = rg.integers(low=0, high=10, size=3)
r

array([6, 2, 7])

In [239]:
# 1부터 6까지 주사위처럼 정수 난수 생성
rg = np.random.default_rng(12345)
r = rg.integers(1, 7, (3, 4))
r

array([[5, 2, 5, 2],
       [2, 5, 4, 5],
       [6, 3, 6, 2]])

In [240]:
# 위치 인자로 정수 난수 생성
r = rg.integers(1, 10, (2, 8))
r

array([[6, 6, 2, 2, 3, 7, 6, 9],
       [7, 3, 9, 9, 7, 7, 2, 1]])

In [241]:
# 키워드 인자로 정수 난수 생성
rg = np.random.default_rng(12)
rg.integers(low=1, high=10, size=(2, 8))

array([[6, 3, 9, 9, 1, 2, 2, 2],
       [6, 4, 5, 3, 9, 7, 6, 2]])

### 5. `standard_normal()` : 표준정규분포 난수

- 평균 0, 표준편차 1인 정규분포 난수
- 데이터 분석이나 시뮬레이션에서 자주 사용

In [242]:
# 표준정규분포 난수 10개
rg = np.random.default_rng(12)
rg.standard_normal(10)

array([-0.007,  1.046,  0.742,  0.724,  1.619, -1.206, -0.627, -1.321,
       -0.108,  0.999])

In [243]:
# 3행 4열 표준정규분포 난수
rg.standard_normal((3, 4))

array([[-0.022,  0.496, -1.911,  0.147],
       [-0.907,  1.775,  0.887,  0.949],
       [-0.058,  0.613,  0.658, -0.344]])

In [244]:
# 10행 5열 표준정규분포 난수
rg.standard_normal((10, 5))

array([[-0.497, -0.115, -0.605, -0.594, -0.283],
       [-0.728,  0.766, -1.596,  0.824, -0.626],
       [-0.546, -1.351, -0.144, -0.248,  0.191],
       [-0.534,  0.094,  1.82 ,  0.409, -0.574],
       [ 0.953, -0.129,  0.594,  0.613, -0.391],
       [-1.93 , -0.348,  0.551, -0.38 ,  0.439],
       [ 0.98 , -0.544,  1.231,  1.622,  1.079],
       [ 1.165,  1.097,  2.255,  0.186,  0.002],
       [ 0.603, -0.908, -1.553, -0.882,  0.373],
       [ 0.473, -1.536, -1.883, -0.316, -0.188]])